In [44]:
import pandas as pd

In [45]:
df=pd.read_excel("Raisin_Dataset.xlsx")

In [46]:
df.sample(5)

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter,Class
211,46961,343.788528,177.136795,0.857040,48476,0.614633,891.528,Kecimen
719,110527,514.588849,275.583355,0.844509,114538,0.689699,1360.821,Besni
408,82793,428.116905,249.390880,0.812809,84950,0.742458,1130.673,Kecimen
280,58857,320.811908,235.386045,0.679452,60597,0.690364,927.048,Kecimen
325,34977,267.737739,170.837246,0.769973,37747,0.669480,754.366,Kecimen

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X = df.drop("Class", axis=1)  # features
y=df["Class"]

In [49]:
X.head()

,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,Extent,Perimeter
0,87524,442.246011,253.291155,0.819738,90546,0.758651,1184.040
1,75166,406.690687,243.032436,0.801805,78789,0.684130,1121.786
2,90856,442.267048,266.328318,0.798354,93717,0.637613,1208.575
3,45928,286.540559,208.760042,0.684989,47336,0.699599,844.162
4,79408,352.190770,290.827533,0.564011,81463,0.792772,1073.251

## Scaling

In [50]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=10)

In [51]:
from sklearn.preprocessing import  MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X)
X_train_scaled=scaler.transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [52]:
X_train_scaled

array([[0.48059716, 0.3281844 , 0.58011976, ..., 0.43097375, 0.53786893,
        0.44745293],
       [0.56281122, 0.31574296, 0.72755368, ..., 0.4767929 , 0.81300587,
        0.38627417],
       [0.31659353, 0.26972756, 0.36313295, ..., 0.2671435 , 0.68715875,
        0.26267163],
       ...,
       [0.65847086, 0.47835644, 0.59591516, ..., 0.56066773, 0.71297362,
        0.48246266],
       [0.13798054, 0.16351156, 0.15694846, ..., 0.11830068, 0.60588261,
        0.14988028],
       [0.25515597, 0.21961749, 0.32491583, ..., 0.21752791, 0.65538111,
        0.22785384]], shape=(720, 7))

## unscaled

In [53]:
from sklearn.svm import SVC
model = SVC(kernel="rbf")
model.fit(X,y)
y_pred=model.predict(X_test)
from sklearn.metrics import classification_report
cm=classification_report(y_test,y_pred)
print(cm)
model.n_iter_

              precision    recall  f1-score   support

       Besni       0.85      0.75      0.79        83
     Kecimen       0.80      0.89      0.84        97

    accuracy                           0.82       180
   macro avg       0.83      0.82      0.82       180
weighted avg       0.82      0.82      0.82       180

array([301], dtype=int32)

## unscaled

In [54]:
from sklearn.svm import SVC
model = SVC(kernel="rbf")
model.fit(X_train_scaled,y_train)
y_pred=model.predict(X_test_scaled)
from sklearn.metrics import classification_report
cm=classification_report(y_test,y_pred)
print(cm)
model.n_iter_

              precision    recall  f1-score   support

       Besni       0.95      0.83      0.88        83
     Kecimen       0.87      0.96      0.91        97

    accuracy                           0.90       180
   macro avg       0.91      0.90      0.90       180
weighted avg       0.90      0.90      0.90       180

array([231], dtype=int32)

In [55]:
from sklearn.pipeline import Pipeline
pipeline=Pipeline([
    ('scaler',MinMaxScaler()),
    ('SVC',SVC(kernel='rbf'))
])

In [57]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('scaler', MinMaxScaler()), ('SVC', SVC())])

In [59]:
y_pred=pipeline.predict(X_test)

In [60]:
from sklearn.metrics import classification_report

In [61]:
cm=classification_report(y_test,y_pred)

In [62]:
print(cm)

              precision    recall  f1-score   support

       Besni       0.94      0.82      0.88        83
     Kecimen       0.86      0.96      0.91        97

    accuracy                           0.89       180
   macro avg       0.90      0.89      0.89       180
weighted avg       0.90      0.89      0.89       180