In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("home_prices.csv")
df.head()

   area_sqr_ft  bedrooms color  price_lakhs
0         3774         2   Red          216
1         1460         3  Gray           88
2         1894         4  Gray          147
3         1730         2  Blue           84
4         1695         1  Blue           77

In [7]:
df_encoded=pd.get_dummies(df,columns=['color'],drop_first=True)

In [8]:
df_encoded.head()

,area_sqr_ft,bedrooms,price_lakhs,color_Gray,color_Green,color_Red,color_White,color_Yellow
0,3774,2,216,False,False,True,False,False
1,1460,3,88,True,False,False,False,False
2,1894,4,147,True,False,False,False,False
3,1730,2,84,False,False,False,False,False
4,1695,1,77,False,False,False,False,False

In [10]:
cm=df_encoded.corr()

In [11]:
cm.head()

,area_sqr_ft,bedrooms,price_lakhs,color_Gray,color_Green,color_Red,color_White,color_Yellow
area_sqr_ft,1.000000,0.185810,0.945365,-0.068944,-0.032012,0.059055,0.063827,-0.037819
bedrooms,0.185810,1.000000,0.439445,0.040882,-0.120207,-0.004177,-0.023676,0.015286
price_lakhs,0.945365,0.439445,1.000000,-0.040565,-0.041959,0.045803,0.051122,-0.046673
color_Gray,-0.068944,0.040882,-0.040565,1.000000,-0.214409,-0.230990,-0.205931,-0.217205
color_Green,-0.032012,-0.120207,-0.041959,-0.214409,1.000000,-0.190117,-0.169493,-0.178771

In [13]:
cm_price=abs(cm['price_lakhs'])

In [14]:
cm_price

area_sqr_ft     0.945365
bedrooms        0.439445
price_lakhs     1.000000
color_Gray      0.040565
color_Green     0.041959
color_Red       0.045803
color_White     0.051122
color_Yellow    0.046673
Name: price_lakhs, dtype: float64

In [15]:
cm_price>0.2

area_sqr_ft      True
bedrooms         True
price_lakhs      True
color_Gray      False
color_Green     False
color_Red       False
color_White     False
color_Yellow    False
Name: price_lakhs, dtype: bool

In [25]:
selected_features=cm_price[cm_price>0.2].index.drop('price_lakhs')

In [28]:
X=df[selected_features]
y = df['price_lakhs']

In [29]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("R2:", r2, "MSE:", mse)

R2: 0.9689466488379601 MSE: 76.63332198278805