In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Lasso , Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [3]:
df=pd.read_csv("dataset.csv")

In [4]:
df.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f142,f143,f144,f145,f146,f147,f148,f149,f150,target
0,-0.924357,-0.326536,-1.875007,-1.780626,-0.630143,0.788204,2.792209,-0.772192,-0.450994,0.400000,...,0.968645,-0.702053,-0.327662,-0.392108,-1.463515,0.296120,0.261055,0.005113,-0.234587,10.681366
1,0.001795,-1.285599,-0.726774,0.385711,0.891863,0.599451,-0.140553,-0.761760,0.117707,0.333231,...,0.856399,0.214094,-1.245739,0.173181,0.385317,-0.883857,0.153725,0.058209,-1.142970,-60.163343
2,0.956702,2.319330,-0.705012,0.081829,0.330880,0.838491,2.493000,1.227669,-0.785989,-0.920674,...,-0.493001,-0.589365,0.849602,0.357015,-0.692910,0.899600,0.307300,0.812862,0.629629,131.226545
3,-0.982294,0.190424,1.082691,0.714610,-1.907808,0.224216,0.156973,0.556553,0.058984,-1.397118,...,0.491919,-1.320233,1.831459,1.179440,-0.469176,-1.713135,1.353872,-0.114540,1.237816,-131.889020
4,-0.057061,-0.592465,-2.850030,-1.935430,2.002427,-1.012644,1.059950,-1.000629,0.141596,-0.642776,...,1.479944,0.077368,-0.861284,1.523124,0.538910,-1.037246,-0.190339,-0.875618,-1.382800,-138.566956

In [8]:
X=df.drop(["target"], axis= 1)
y=df["target"]
X.head(3)

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f141,f142,f143,f144,f145,f146,f147,f148,f149,f150
0,-0.924357,-0.326536,-1.875007,-1.780626,-0.630143,0.788204,2.792209,-0.772192,-0.450994,0.400000,...,0.097078,0.968645,-0.702053,-0.327662,-0.392108,-1.463515,0.296120,0.261055,0.005113,-0.234587
1,0.001795,-1.285599,-0.726774,0.385711,0.891863,0.599451,-0.140553,-0.761760,0.117707,0.333231,...,-0.446515,0.856399,0.214094,-1.245739,0.173181,0.385317,-0.883857,0.153725,0.058209,-1.142970
2,0.956702,2.319330,-0.705012,0.081829,0.330880,0.838491,2.493000,1.227669,-0.785989,-0.920674,...,-0.208122,-0.493001,-0.589365,0.849602,0.357015,-0.692910,0.899600,0.307300,0.812862,0.629629

In [9]:
X_train, X_test, y_train,y_test=train_test_split(X,y,test_size=0.25, random_state=42)

In [11]:
lm=LinearRegression()
lm.fit(X_train,y_train)
lm.score(X_test,y_test)

0.7410183335246907

In [19]:
lm.coef_, lm.intercept_

(array([ 30.5502605 , -37.91397171,  14.17527214,   0.78083357,
          3.75133524, -31.13869527,  53.68852306,  93.56466317,
        -31.5825238 , -11.38841381, -35.6784998 ,  40.67375848,
          3.62031963,  -2.09903202, -15.31981974,   6.6902648 ,
         20.24051312, -17.5043733 ,  42.82135882,  66.27388457,
        -39.58548175,   5.94205081,  46.0650318 ,  31.54007432,
         -2.44446922,  -4.2212642 ,   0.59286811,   3.92334798,
         -5.01154922,   3.93937364,   3.92330605,  -7.34764566,
         86.817593  ,   0.41148934,  -3.2867563 ,  -3.07684278,
          4.37177689,   5.2605021 ,  -3.52721952,   9.17214331,
          6.12833853,   5.46983655,  -0.86360751,  -0.73634359,
         -3.0067608 ,  -1.31766726,  -5.37890201,   3.1123997 ,
         -1.04391302,   1.61670639, -28.23622443,  38.83799572,
          9.38775063,  -2.67626335,  26.0003329 ,  23.04033092,
        -54.04279193, -28.21843994,  19.08259729,  13.25052065,
         21.28068869, -39.44894727, -11.08479556,  -3.94083092,
         12.5233143 ,  -5.29621333,  12.93649639,  18.16838045,
        -40.99700089,   1.86484489,  29.52465395,  -0.60875437,
        -47.56273995, -21.16797354,  -2.72626249,   5.81368678,
         -3.04104575,   0.87317534,  -0.73794143,  -1.87363815,
          2.40207155,  -3.77087696,   0.64215438,   7.01155184,
          1.83944806,   2.57685475,  10.83476007,   2.72537537,
          7.8144321 ,   3.82879094,   5.15895348,   8.13977779,
         -2.47066721,   7.91221401,  -2.30336063,   8.4234507 ,
          6.32545984,   1.594731  , -10.2580694 ,   0.30848489,
          0.50461854,   2.76952208,   2.19633993,   1.44952423,
          4.66079026,   1.53707697,   3.46664606, -10.09182367,
          3.85832303,   3.51863836,   1.10276581,  -3.43593973,
         13.3620698 ,  -3.23612976,   0.59743475, -10.75961705,
         -0.51764458,  -1.11988028,  -2.58909455,  -7.76642975,
         -0.78398778,   0.83854905,   7.43261421,   8.11037895,
         -4.31998527,   3.18740428,  -4.22708942,  -1.3279312 ,
          0.72960122,  -9.58956299,  -3.11293898, -13.27084129,
          2.4186831 ,  -7.64790173,  -1.4410984 ,   5.09992737,
         -2.40476917,  -5.03742364,  -4.89445049,  -0.5978738 ,
         -2.11188224,  -2.80527747,  -5.47739367,  -4.79262174,
          6.81555319,  -7.49020894,  -5.10332914,   1.4213112 ,
          8.2619979 ,  -9.67458169]),
 np.float64(-3.1531141806647245))

In [12]:
lasso_m=Lasso(alpha=1.0)
lasso_m.fit(X_train,y_train)
lasso_m.score(X_test,y_test)

0.9901476660336155

In [14]:
Ridge_m=Ridge(alpha=1.5)
Ridge_m.fit(X_train,y_train)
Ridge_m.score(X_test,y_test)

0.9451781077001787